version: "3.9"

networks:
  rproxy:

services:
  octolo_back:
    image: python:3.11.0rc2-slim-bullseye
    container_name: octolo_back
    volumes:
      - ./back:/opt/app
    working_dir: /opt/app
    restart: unless-stopped
    entrypoint: /bin/sh entrypoint.sh
    ports:
      - 8000:8000
    networks:
      - rproxy

  octolo_front:
    image: node:16-alpine
    container_name: octolo_front
    volumes:
      - ./front:/opt/app
    working_dir: /opt/app
    restart: unless-stopped
    entrypoint: /bin/sh entrypoint.sh
    networks:
      - rproxy

  nginx-rproxy:
    image: nginx:1.21.5-alpine
    networks:
      - rproxy
    volumes:
      - ./rproxy.nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    restart: unless-stopped
    depends_on:
      - octolo_back
      - octolo_front
